#pragma once

#include <windows.h>

// IOCP Completion Key
const ULONG_PTR CK_SHUTDOWN = 0;
const ULONG_PTR CK_ACCEPT = 1;
const ULONG_PTR CK_RIO = 2;

const USHORT SERVER_PORT = 13577;
const DWORD ADDR_LEN = sizeof(SOCKADDR_IN) + 16;
const ULONG MAX_CONNECTIONS_COUNT = 1024;
const ULONG ACCEPT_POOL_SIZE = 16;
const ULONG BUFFER_SIZE = 4096;
const ULONG MAX_PENDING_RECVS = 1;
const ULONG MAX_PENDING_SENDS = 1;
const ULONG CQ_SIZE = MAX_CONNECTIONS_COUNT * (MAX_PENDING_RECVS + MAX_PENDING_SENDS);
const ULONG RIO_RESULTS_SIZE = 256;